# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "7c807647-f014-431d-aeb1-c995d23c4826",
# META       "default_lakehouse_name": "demo_lh",
# META       "default_lakehouse_workspace_id": "f0bae9f7-35d7-42ad-b24d-31286c19623c",
# META       "known_lakehouses": [
# META         {
# META           "id": "7c807647-f014-431d-aeb1-c995d23c4826"
# META         }
# META       ]
# META     },
# META     "environment": {}
# META   }
# META }

# CELL ********************

df = spark.sql("SELECT * FROM demo_lh.poc_data LIMIT 1000")
display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.explain(True)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

from pyspark.sql import SparkSession

spark = (
    SparkSession.builder
    .appName("sparklens-demo")
    .config("spark.jars", "Files/sparklens_2.12-0.3.2.jar")
    .config("spark.extraListeners", "com.qubole.sparklens.QuboleJobListener")
    .getOrCreate()
)
sc = spark.sparkContext


# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import functions as F
from pyspark.sql import types as T

def clean_data(df):
    # Capitalize the first character in column: 'bu_intersection'
    udf_capitalize = F.pandas_udf(lambda x: x.str.capitalize(), T.StringType())
    df = df.withColumn('bu_intersection', udf_capitalize('bu_intersection'))
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

#### ATTENTION: AI-generated code can include errors or operations you didn't intend. Review the code in this cell carefully before running it.

# Import necessary libraries
from pyspark.sql import SparkSession
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml.classification import RandomForestClassifier
from pyspark.ml import Pipeline
import pandas as pd

# Initialize Spark session
spark = SparkSession.builder.appName("Feature Importance in poc_data").getOrCreate()

# Load the poc_data table
spark_df = spark.read.table("poc_data").limit(1000)

# Data Preparation
# Handling Missing Values
# Impute missing values with mode for categorical and mean for numerical columns
categorical_columns = [item[0] for item in spark_df.dtypes if item[1].startswith('string')]
numerical_columns = [item[0] for item in spark_df.dtypes if item[1].startswith('int') or item[1].startswith('double')]

# Encoding Categorical Variables using StringIndexer
indexers = [StringIndexer(inputCol=column, outputCol=column+"_index").fit(spark_df) for column in categorical_columns]

# Convert Data Types
# Convert 'injected_time' to datetime
spark_df = spark_df.withColumn("injected_time", to_date(col("injected_time"), 'M/d/yyyy H:m'))

# Create a VectorAssembler to combine feature columns into a single vector
assembler = VectorAssembler(inputCols=[col+"_index" for col in categorical_columns] + numerical_columns, outputCol="features")

# Specify a classifier: RandomForestClassifier
rf = RandomForestClassifier(labelCol="qualified_status", featuresCol="features")

# Create a pipeline with indexers and the classifier
pipeline = Pipeline(stages=indexers + [assembler, rf])

# Train the model
model = pipeline.fit(spark_df)

# Extract feature importances
rf_model = model.stages[-1]
importances = rf_model.featureImportances.toArray()

# Create a DataFrame with feature names and their respective importances
feature_names = [col+"_index" for col in categorical_columns] + numerical_columns
feature_importances = pd.DataFrame(list(zip(feature_names, importances)), columns=["Feature", "Importance"]).sort_values(by="Importance", ascending=False)

# Display the most important features
print(feature_importances.head(10))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# ATTENTION: AI-generated code can include errors or operations you didn't intend. Review the code in this cell carefully before running it.

#### ATTENTION: AI-generated code can include errors or operations you didn't intend. Review the code in this cell carefully before running it.

# Read the 'poc_data' table into a Spark DataFrame and display the top 10 rows
spark_df = spark.read.table("poc_data")
display(spark_df.limit(10))

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
